version: '3.4'

services:
  database:
    container_name: database
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fabrica
      POSTGRES_USER: admin
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      - bridge

  php:
    container_name: php
    build:
      context: ./docker/php
    depends_on:
      - database
    volumes:
      - ./:/var/www
      - ./docker/logs/supervisor:/var/log/supervisor
    networks:
      - bridge

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    volumes:
      - /docker/rabbitmq/data/:/var/lib/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - bridge
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - bridge

volumes:
  db_data:

networks:
  bridge:
